project:
  type: website
  output-dir: docs
  
website:
  page-navigation: true
  title: "Wu Keping"
  site-url: https://wukeping99-svg.github.io
  favicon: images/site-logo.png
  repo-url: 'edit'
  repo-actions: 'edit'

  
  page-footer:
    left: 'edit'
     
    right: 'edit'
    
    
  navbar: 
    background: "#A9CCE3"
    search: true
    right: 
      - text: "Home"
        href: index.qmd
      - text: "Publications"
        href: publications.qmd
      - text: "Books"
        href: books.qmd
      - text: "Blogs"
        href: blog.qmd
      - text: "Codes"
        href: codes.qmd
      - text: "中文"
        href: Chinese.qmd
      - text: "CV"
        href: CV.pdf

format:
  html:
    theme: styles.scss
    toc: true            # 启用目录
    toc-position: right  # 将目录放置在页面的右侧
    toc-depth: 3         # 设置目录的深度，数字越大，目录越详细